#!/bin/sh

previewdir="$XDG_CONFIG_HOME/ncmpcpp/previews"
filename="$(mpc --format ~/audio/music/%file% current)"
previewname="$(mpc --format %album% current)"
fullpath="/home/kweint/.config${previewdir}/${previewname}.png"
echo "$fullpath"

[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf scale=528:528 "$previewname" > /dev/null 2>&1

if test -f "$fullpath"; then
	dunstify -a ncmpcpp -r 27072 "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" -i "$previewname" -t 2500
else
	dunstify -a ncmpcpp -r 27072 "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" -t 2500 -i default
fi
