#!/bin/bash
# relaunch DWM if the binary changes, otherwise bail
csum=""
new_csum=$(sha1sum /home/dennis/bin/dwm)
while true
do
   ./startconfig &
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        /home/dennis/bin/dwm
    else
        exit 0
    fi
    new_csum=$(/home/dennis/bin/dwm)
    sleep 0.5
done
